FROM python:3.7

RUN apt-get update && apt-get install -y \
    libsm6 libxext6  

RUN mkdir /code
WORKDIR /code
COPY ./requirements.txt .
RUN pip install -r requirements.txt
COPY ./bullet3/. ./bullet3
COPY ./cartpolepp/. ./cartpolepp
COPY ./objects/. ./objects
COPY ./*.py ./
COPY ./evm_config.json ./


WORKDIR bullet3
RUN bash build_cmake_pybullet_double.sh
RUN cp ./build_cmake/examples/pybullet/pybullet.so.3.19 \
 /usr/local/lib/python3.7/site-packages/pybullet.cpython-37m-x86_64-linux-gnu.so

WORKDIR /code
